# .github/workflows/build-client.yml
name: Client Build Check

on:
  push:
    branches: [main, '**']  # run on all branches
  pull_request:             # run on PRs

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or whatever version you need

      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Run build
        working-directory: ./
        run: npm run build
