name: Build React + Flask Docker Image to Production Branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build React
        run: |
          cd client
          npm install
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t flask-react-app .

      - name: Commit React build and Dockerfile to production branch
        run: |
          mkdir -p temp-build
          cp -r client/build/* temp-build/

          # Set git config for committing
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Checkout production branch, create if it doesn't exist
          git checkout --orphan production || git checkout production

          # Remove any old files and copy new build
          git rm -rf .
          cp -r temp-build/* .
          cp -r Dockerfile ./ # Include Dockerfile in production branch

          # Commit the changes (React build and Docker)
          git add .
          git commit -m "Add React build and Docker image"

          # Push changes to production branch
          git push -f origin production
