# .github/workflows/staging.yml
name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING }}
    secrets:
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
