# .github/workflows/production.yml
name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      branch: main
      dokku_host: ${{ secrets.DOKKU_HOST_PRODUCTION }}
      dokku_app: ${{ secrets.DOKKU_APP_PRODUCTION }}
    environment:
      name: production
