name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    # Prevents this from being triggered from a fork (extra safety)
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'
    runs-on: [self-hosted, staging-runner]  # <-- customize this label to match your runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY_STAGING }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DOKKU_HOST_STAGING }} >> ~/.ssh/known_hosts

      - name: Deploy to Dokku Staging
        run: |
          git remote add dokku dokku@${{ secrets.DOKKU_HOST_STAGING }}:${{ secrets.DOKKU_APP_STAGING }}
          git push dokku HEAD:main -f
