name: Deploy to Production

on:
  workflow_dispatch:  # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0  # needed to push branches later

    - name: Set up SSH for Dokku
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DOKKU_SSH_KEY_PRODUCTION }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DOKKU_HOST_PRODUCTION }} >> ~/.ssh/known_hosts

    - name: Deploy main branch to Dokku Production
      run: |
        git remote add dokku dokku@${{ secrets.DOKKU_HOST_PRODUCTION }}:${{ secrets.DOKKU_APP_PRODUCTION }}
        git push dokku HEAD:main -f

    - name: Push main → production branch in GitHub
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git push origin HEAD:production -f
